before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/elk/main.go
  goos:
    - windows
    - linux
    - darwin
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.os={{.Os}} -X main.arch={{.Arch}} -X main.commit={{.ShortCommit}} -X main.date={{.Env.DATE}} -X "main.goversion={{.Env.GOVERSION}}"

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
