dist: bionic

language: go

go:
  - 1.13.x

# Only clone the most recent commit.
git:
  depth: 1

before_script:
  # Install golangci-lint
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.23.1

script:
  - go test ./...

notifications:
  email:
    - jjzcru@gmail.com