// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Dep struct {
	Name     string `json:"name"`
	Detached bool   `json:"detached"`
}

type Elk struct {
	Version string                 `json:"version"`
	Env     map[string]interface{} `json:"env"`
	EnvFile string                 `json:"env_file"`
	Vars    map[string]interface{} `json:"vars"`
	Tasks   []*Task                `json:"tasks"`
}

type Log struct {
	Out    string `json:"out"`
	Format string `json:"format"`
	Error  string `json:"error"`
}

type Output struct {
	Task  string   `json:"task"`
	Out   []string `json:"out"`
	Error []string `json:"error"`
}

type Task struct {
	Name        string                 `json:"name"`
	Cmds        []*string              `json:"cmds"`
	Env         map[string]interface{} `json:"env"`
	Vars        map[string]interface{} `json:"vars"`
	EnvFile     string                 `json:"env_file"`
	Description string                 `json:"description"`
	Dir         string                 `json:"dir"`
	Log         *Log                   `json:"log"`
	Sources     *string                `json:"sources"`
	Deps        []*Dep                 `json:"deps"`
	IgnoreError bool                   `json:"ignore_error"`
}

type TaskProperties struct {
	Vars        map[string]interface{} `json:"vars"`
	Env         map[string]interface{} `json:"env"`
	IgnoreError *bool                  `json:"ignore_error"`
}
