// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Dep struct {
	Name     string `json:"name"`
	Detached bool   `json:"detached"`
}

type DetachedTask struct {
	ID       string        `json:"id"`
	Tasks    []*Task       `json:"tasks"`
	Outputs  []*Output     `json:"Outputs"`
	Status   string        `json:"status"`
	StartAt  time.Time     `json:"startAt"`
	Duration time.Duration `json:"duration"`
	EndAt    *time.Time    `json:"endAt"`
}

type Elk struct {
	Version string                 `json:"version"`
	Env     map[string]interface{} `json:"env"`
	EnvFile string                 `json:"env_file"`
	Vars    map[string]interface{} `json:"vars"`
	Tasks   []*Task                `json:"tasks"`
}

type Log struct {
	Out    string `json:"out"`
	Format string `json:"format"`
	Error  string `json:"error"`
}

type Output struct {
	Task  string   `json:"task"`
	Out   []string `json:"out"`
	Error []string `json:"error"`
}

type RunConfig struct {
	Start    *time.Time     `json:"start"`
	Deadline *time.Time     `json:"deadline"`
	Timeout  *time.Duration `json:"timeout"`
	Delay    *time.Duration `json:"delay"`
}

type Task struct {
	Name        string                 `json:"name"`
	Cmds        []*string              `json:"cmds"`
	Env         map[string]interface{} `json:"env"`
	Vars        map[string]interface{} `json:"vars"`
	EnvFile     string                 `json:"env_file"`
	Description string                 `json:"description"`
	Dir         string                 `json:"dir"`
	Log         *Log                   `json:"log"`
	Sources     *string                `json:"sources"`
	Deps        []*Dep                 `json:"deps"`
	IgnoreError bool                   `json:"ignore_error"`
}

type TaskProperties struct {
	Vars        map[string]interface{} `json:"vars"`
	Env         map[string]interface{} `json:"env"`
	EnvFile     string                 `json:"envFile"`
	IgnoreError *bool                  `json:"ignoreError"`
}
